"""pycolmap round-trip tests for colmap-webview exports.

Fixtures are generated by `npx vite-node tests/pycolmap/generate_fixtures.ts`
and written to `fixtures/<scenario>/sparse/0/*.bin`. These tests load each
scenario through the real pycolmap library (ground truth for the COLMAP
binary format) and verify the files are both loadable and self-consistent.
"""

import json
import os
import subprocess
from pathlib import Path

import numpy as np
import pytest

try:
    import pycolmap
except ImportError:  # pragma: no cover
    pytest.skip(
        "pycolmap not installed — run `uv sync` in tests/pycolmap",
        allow_module_level=True,
    )


HERE = Path(__file__).parent
FIXTURES = HERE / "fixtures"
# colmap-webview project root (where package.json lives)
REPO = HERE.parent.parent
# Parent directory containing the bicycle dataset sibling
WORKSPACE = REPO.parent
BICYCLE = WORKSPACE / "360_v2" / "bicycle" / "sparse" / "0" / "cameras.bin"


def _fixture_path(scenario: str) -> Path:
    return FIXTURES / scenario / "sparse" / "0"


def _regenerate_fixtures() -> None:
    """Run the TS fixture generator via vite-node."""
    # shell=True is required on Windows so .cmd shims (npx.cmd) resolve.
    cmd = "npx vite-node tests/pycolmap/generate_fixtures.ts"
    subprocess.run(cmd, cwd=REPO, check=True, shell=True)


@pytest.fixture(scope="session", autouse=True)
def _ensure_fixtures():
    # Regenerate if the user opts in or if fixtures are missing.
    if os.environ.get("REGEN_FIXTURES") == "1" or not (FIXTURES / "untransformed").exists():
        if not BICYCLE.exists():
            pytest.skip(f"bicycle fixture not present (expected at {BICYCLE})")
        _regenerate_fixtures()


def _count_dangling(rec: "pycolmap.Reconstruction") -> int:
    """Count track elements that reference (image_id, point2D_idx) out of range."""
    dangling = 0
    image_ids = set(rec.images)
    for pid, point in rec.points3D.items():
        for el in point.track.elements:
            if el.image_id not in image_ids:
                dangling += 1
                continue
            img = rec.images[el.image_id]
            if el.point2D_idx >= len(img.points2D):
                dangling += 1
    return dangling


class TestUntransformedRoundtrip:
    def test_loads_without_error(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("untransformed")))
        assert rec.num_images() > 0
        assert rec.num_points3D() > 0
        assert rec.num_cameras() >= 1

    def test_no_dangling_track_refs(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("untransformed")))
        assert _count_dangling(rec) == 0


class TestTransformBakedRoundtrip:
    """Exercises the fix for applyTransformToData (realize points2D before dropping WASM)."""

    def test_loads_without_error(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("transform_baked")))
        assert rec.num_images() > 0
        assert rec.num_points3D() > 0

    def test_no_dangling_track_refs(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("transform_baked")))
        assert _count_dangling(rec) == 0

    def test_image_points2D_populated(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("transform_baked")))
        total = sum(len(img.points2D) for img in rec.images.values())
        assert total > 0, "images have no 2D points after transform bake — fix regressed"

    def test_camera_intrinsics_unchanged_by_transform(self):
        """Sim3D doesn't affect fx/fy/cx/cy — pycolmap sees the same values."""
        orig = pycolmap.Reconstruction(str(_fixture_path("untransformed")))
        baked = pycolmap.Reconstruction(str(_fixture_path("transform_baked")))
        for cid, orig_cam in orig.cameras.items():
            baked_cam = baked.cameras[cid]
            assert baked_cam.model == orig_cam.model
            assert baked_cam.width == orig_cam.width
            assert baked_cam.height == orig_cam.height
            assert list(baked_cam.params) == list(orig_cam.params)


class TestDeletionsAppliedRoundtrip:
    """Exercises the fix for applyDeletionsToData in WASM mode (filter tracks)."""

    def test_loads_without_error(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("deletions_applied")))
        assert rec.num_images() > 0
        assert rec.num_points3D() > 0

    def test_no_dangling_track_refs(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("deletions_applied")))
        assert _count_dangling(rec) == 0

    def test_images_actually_fewer(self):
        orig = pycolmap.Reconstruction(str(_fixture_path("untransformed")))
        filt = pycolmap.Reconstruction(str(_fixture_path("deletions_applied")))
        assert filt.num_images() < orig.num_images()

    def test_tracks_reference_only_surviving_images(self):
        rec = pycolmap.Reconstruction(str(_fixture_path("deletions_applied")))
        image_ids = set(rec.images.keys())
        for point in rec.points3D.values():
            for el in point.track.elements:
                assert el.image_id in image_ids


def _quat_xyzw_to_matrix(q: np.ndarray) -> np.ndarray:
    """Rotation matrix from a quaternion in (x, y, z, w) order."""
    x, y, z, w = q
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


def _camera_world_position(img) -> np.ndarray:
    """Camera center in world space from a pycolmap Image."""
    # pycolmap 3.11: cam_from_world is a method returning a Rigid3d.
    cam_from_world = img.cam_from_world()
    q_xyzw = np.asarray(cam_from_world.rotation.quat)  # (x, y, z, w)
    t = np.asarray(cam_from_world.translation)
    R = _quat_xyzw_to_matrix(q_xyzw)
    # World position = -R^T @ t
    return -R.T @ t


def _apply_sim3d(sim3d: dict, p: np.ndarray) -> np.ndarray:
    """Apply a Sim3D transform P' = scale * R * P + t."""
    q = np.array(sim3d["rotation_quat_xyzw"])
    R = _quat_xyzw_to_matrix(q)
    t = np.array(sim3d["translation"])
    return sim3d["scale"] * (R @ p) + t


class TestCamerasMoveWithPoints:
    """After transform bake, cameras and 3D points are transformed by the same
    Sim3D. pycolmap should see each camera's world position at the expected
    location, and each 3D point at its expected location — so the relative
    geometry (distances, projection rays) is preserved. This guards against
    regressions where cameras and points drift apart after export."""

    @pytest.fixture(scope="class")
    def sim3d(self):
        sidecar = FIXTURES / "transform_baked" / "sim3d.json"
        return json.loads(sidecar.read_text())["sim3d"]

    @pytest.fixture(scope="class")
    def orig(self):
        return pycolmap.Reconstruction(str(_fixture_path("untransformed")))

    @pytest.fixture(scope="class")
    def baked(self):
        return pycolmap.Reconstruction(str(_fixture_path("transform_baked")))

    def test_camera_world_positions_match_expected(self, orig, baked, sim3d):
        # For every image, pycolmap's computed baked camera center should equal
        # Sim3D applied to the original camera center.
        assert set(orig.images) == set(baked.images)
        max_err = 0.0
        for image_id in orig.images:
            orig_C = _camera_world_position(orig.images[image_id])
            baked_C = _camera_world_position(baked.images[image_id])
            expected_C = _apply_sim3d(sim3d, orig_C)
            err = float(np.linalg.norm(baked_C - expected_C))
            max_err = max(max_err, err)
        assert max_err < 1e-6, f"camera positions drifted; max L2 err={max_err}"

    def test_point3d_positions_match_expected(self, orig, baked, sim3d):
        # Every surviving 3D point should be transformed by the same Sim3D.
        shared = set(orig.points3D) & set(baked.points3D)
        assert len(shared) > 1000, "too few shared point IDs — export reordered?"
        sampled = list(shared)[::100]  # every 100th point; cheap sanity
        max_err = 0.0
        for pid in sampled:
            orig_xyz = np.array(orig.points3D[pid].xyz)
            baked_xyz = np.array(baked.points3D[pid].xyz)
            expected_xyz = _apply_sim3d(sim3d, orig_xyz)
            err = float(np.linalg.norm(baked_xyz - expected_xyz))
            max_err = max(max_err, err)
        assert max_err < 1e-6, f"points3D drifted; max L2 err={max_err}"

    def test_camera_to_point_distances_scale_by_sim3d_scale(self, orig, baked, sim3d):
        # For any camera and any observed point, the ratio of baked distance to
        # original distance must equal sim3d.scale. This is the invariant a user
        # means when they say "cameras are aligned to the point cloud".
        scale = sim3d["scale"]
        sample_image_ids = list(orig.images)[:5]
        tolerances = []
        for image_id in sample_image_ids:
            orig_C = _camera_world_position(orig.images[image_id])
            baked_C = _camera_world_position(baked.images[image_id])
            orig_img_points = list(orig.images[image_id].points2D)
            if not orig_img_points:
                continue
            for p2d in orig_img_points[::200]:
                if p2d.point3D_id == 18446744073709551615 or p2d.point3D_id not in orig.points3D:
                    continue
                orig_P = np.array(orig.points3D[p2d.point3D_id].xyz)
                if p2d.point3D_id not in baked.points3D:
                    continue
                baked_P = np.array(baked.points3D[p2d.point3D_id].xyz)
                d_orig = float(np.linalg.norm(orig_P - orig_C))
                d_baked = float(np.linalg.norm(baked_P - baked_C))
                if d_orig < 1e-6:
                    continue
                ratio = d_baked / d_orig
                tolerances.append(abs(ratio - scale))
        assert tolerances, "no camera-point pairs found to check"
        assert max(tolerances) < 1e-5, (
            f"camera-to-point distances did not scale uniformly; max deviation "
            f"from sim3d.scale ({scale}) = {max(tolerances)}"
        )


class TestBugState:
    """Negative control: the pre-fix bug state must still be broken.

    The fixture reproduces the exact shape of the user's reported crash —
    images with empty points2D arrays plus points3D whose tracks reference
    those images. pycolmap refuses to construct a Reconstruction from it,
    throwing the exact `IndexError` the user saw ("invalid vector
    subscript" / `__n >= size() (0)`).

    If this test starts passing (i.e. no exception raised), one of the
    fixes regressed or the fixture generator stopped reproducing the bug.
    """

    def test_pycolmap_rejects_the_pre_fix_export(self):
        path = _fixture_path("bug_empty_points2D")
        with pytest.raises(IndexError):
            pycolmap.Reconstruction(str(path))
