import { useFrame } from '@react-three/fiber';
import {
  tickGifRecordingFrame,
  tickMediaRecorderRecordingFrame,
  tickWebCodecsRecordingFrame,
  type ScreenshotRecordingFrameLoopOptions,
} from './screenshotRecordingFrameTicks';

export {
  tickGifRecordingFrame,
  tickMediaRecorderRecordingFrame,
  tickWebCodecsRecordingFrame,
  type GifRecordingFrameTickOptions,
  type MediaRecorderRecordingFrameTickOptions,
  type ScreenshotRecordingFrameLoopOptions,
  type WebCodecsRecordingFrameTickOptions,
} from './screenshotRecordingFrameTicks';

export function useScreenshotRecordingFrameLoop({
  gl,
  scene,
  camera,
  addLogoToCanvas,
  screenshotHideLogo,
  gifRef,
  gifStartTimeRef,
  gifLastFrameTimeRef,
  gifDurationMsRef,
  gifDownsampleFactorRef,
  gifSpeedFactorRef,
  gifFrameCountRef,
  videoEncoderRef,
  webCodecsCanvasRef,
  webCodecsStartTimeRef,
  webCodecsDurationMsRef,
  webCodecsSpeedFactorRef,
  webCodecsFrameCountRef,
  webCodecsLastFrameTimeRef,
  isRecordingWebCodecsRef,
  webmRecorderRef,
  webmCanvasRef,
  webmStartTimeRef,
  webmDurationMsRef,
  isRecordingWebmRef,
  webmSpeedFactorRef,
  webmLastFrameTimeRef,
  lastProgressNotificationTimeRef,
  showProgressNotification,
  finishWebCodecsRecording,
  setGifRenderProgress,
  setIsRecordingGif,
  warn,
  errorLog,
  log,
}: ScreenshotRecordingFrameLoopOptions): void {
  useFrame(() => {
    tickGifRecordingFrame({
      gl,
      scene,
      camera,
      addLogoToCanvas,
      screenshotHideLogo,
      gifRef,
      gifStartTimeRef,
      gifLastFrameTimeRef,
      gifDurationMsRef,
      gifDownsampleFactorRef,
      gifSpeedFactorRef,
      gifFrameCountRef,
      lastProgressNotificationTimeRef,
      showProgressNotification,
      setGifRenderProgress,
      setIsRecordingGif,
      warn,
      errorLog,
    });

    tickWebCodecsRecordingFrame({
      gl,
      scene,
      camera,
      addLogoToCanvas,
      screenshotHideLogo,
      videoEncoderRef,
      webCodecsCanvasRef,
      webCodecsStartTimeRef,
      webCodecsDurationMsRef,
      webCodecsSpeedFactorRef,
      webCodecsFrameCountRef,
      webCodecsLastFrameTimeRef,
      isRecordingWebCodecsRef,
      lastProgressNotificationTimeRef,
      showProgressNotification,
      finishWebCodecsRecording,
      warn,
      log,
    });

    tickMediaRecorderRecordingFrame({
      gl,
      scene,
      camera,
      addLogoToCanvas,
      screenshotHideLogo,
      webmRecorderRef,
      webmCanvasRef,
      webmStartTimeRef,
      webmDurationMsRef,
      isRecordingWebmRef,
      webmSpeedFactorRef,
      webmLastFrameTimeRef,
      lastProgressNotificationTimeRef,
      showProgressNotification,
      warn,
    });
  });
}
